# -*- coding: iso-8859-2-unix -*-


sudo: required

jobs:
  include:
    - os: linux
      dist: trusty
    - os: osx
    - os: windows
  allow_failures:
    -os: osx
    -os: windows
dist: trusty

env:
  global:
   - secure: "DmQ3DTsvvKEg30be9kGbbGHkj1xMv5/hQOjXnaP091+lXdtqrHRwN8/Xki2qxyMeaCE3iq8UNVzppd9w/g1z75O63X96K+igVQqdXI5BHtqlKLZonTGMFVqsThjCys2oqRdfxpiZ+ggbImbzFwPqhKCtIeoQTFfDMJSpDpwl9eU="

addons:
  coverity_scan:
    project:
      name: "ralovich/antpm"
      description: "ANT+minus Build submitted via Travis CI"
    notification_email: kristof@ralovich.hu
    build_command_prepend: "pwd && cd cmake-build && pwd && cmake ../src -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_TEST=TRUE"
    build_command:   "make"
    branch_pattern: coverity_scan
    build_script_url: "https://raw.githubusercontent.com/ralovich/antpm/master/scripts/coverity_scan_script.sh"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
    - cmake
    - pkg-config
    - libusb-1.0-0-dev
    - libxml2-dev
    - libboost1.55-dev
    - libboost1.55-all-dev
    - libboost-atomic1.55-dev
    - libboost-date-time1.55-dev
    - libboost-exception1.55-dev
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost-thread1.55-dev
    - valgrind
    - ninja

language: cpp
script: cmake
compiler:
  - gcc
  - clang
notifications:
  email:
    recipients:
      - kristof@ralovich.hu
    on_success: always
    on_failure: always
branches:
  only:
    - master
    - coverity_scan

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx1" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx1" ]; then brew install valgrind boost@1.55; fi
install:

before_script:
  - mkdir cmake-build
script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./scripts/travis_osx.sh; fi
  - travis_wait if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./scripts/travis_trusty.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then echo "asd"; fi

